theme: "just-the-docs"

title: "L3: course material"


footer_content: "Material on this site includes contributions from Daniel Libatique, Dominic Machado,Neel Smith, Timothy Joseph and Natasha Binek, and and available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a> "


aux_links:
  "L3 textbook": 
    - "https://lingualatina.github.io/textbook/"
  "L3 home":
    - "https://lingualatina.github.io/"
